[package]
name = "winter-fri"
version = "0.1.0"
description = "Implementation of FRI protocol for Winterfell STARK prover/verifier"
authors = ["winterfell contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/novifinancial/winterfell"
categories = ["cryptography"]
keywords = ["crypto", "polynomial", "commitments"]
edition = "2018"

[lib]
bench = false

[[bench]]
name = "prover"
harness = false

[[bench]]
name = "folding"
harness = false

[features]
alloc = ["crypto/alloc", "math/alloc", "utils/alloc"]
concurrent = ["crypto/concurrent", "utils/concurrent", "std"]
default = ["std"]
std = ["crypto/std", "math/std", "utils/std"]

[dependencies]
utils = { path = "../utils", package = "winter-utils", default-features = false }
math = { path = "../math", package = "winter-math", default-features = false }
crypto = { path = "../crypto", package = "winter-crypto", default-features = false }

[dev-dependencies]
criterion = "0.3"
