[package]
name = "winter-air"
version = "0.1.0"
description = "AIR components for the Winterfell STARK prover/verifier"
authors = ["winterfell contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/novifinancial/winterfell"
categories = ["cryptography"]
keywords = ["crypto", "arithmetization", "air"]
edition = "2018"

[lib]
bench = false

[dependencies]
utils = { path = "../utils", package = "winter-utils" }
math = { path = "../math", package = "winter-math" }
crypto = { path = "../crypto", package = "winter-crypto" }
fri = { path = "../fri", package = "winter-fri" }

[dev-dependencies]
rand = "0.8"

# Allow math in docs
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", ".cargo/katex-header.html"]