[package]
name = "winterfell"
version = "0.1.0"
description = "Examples of using Winterfell STARK prover/verifier"
authors = ["winterfell contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/novifinancial/winterfell"
categories = ["cryptography"]
edition = "2018"

[lib]
bench = false

[[bin]]
name = "winterfell"
path = "src/main.rs"
bench = false

[features]
concurrent = ["prover/concurrent", "rayon"]

[dependencies]
prover = { path = "../prover" }
verifier = { path = "../verifier" }
hex = "0.4"
log = "0.4"
blake3 = "0.3"
env_logger = "0.8"
bincode = "1.3"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
rayon = { version = "1.5", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "fibonacci"
harness = false

[[bench]]
name = "rescue"
harness = false