[package]
name = "winter-verifier"
version = "0.1.0"
description = "Winterfell STARK verifier"
authors = ["winterfell contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/novifinancial/winterfell"
categories = ["cryptography"]
keywords = ["crypto", "zkp", "stark", "verifier"]
edition = "2018"

[lib]
bench = false

[dependencies]
utils = { path = "../utils", package = "winter-utils" }
math = { path = "../math", package = "winter-math" }
crypto = { path = "../crypto", package = "winter-crypto" }
fri = { path = "../fri", package = "winter-fri" }
air = { path = "../air", package = "winter-air" }
