[package]
name = "winter-crypto"
version = "0.1.0"
description = "Cryptographic library for the Winterfell STARK prover/verifier"
authors = ["winterfell contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/novifinancial/winterfell"
categories = ["cryptography"]
keywords = ["crypto", "merkle-tree", "hash"]
edition = "2018"

[lib]
bench = false

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "merkle"
harness = false
required-features = ["concurrent"]

[features]
alloc = ["hashbrown", "math/alloc", "utils/alloc"]
default = ["std"]
concurrent = ["rayon"]
std = ["blake3/std", "math/std", "utils/std", "sha3/std"]

[dependencies]
utils = { path = "../utils", package = "winter-utils", default-features = false }
math = { path = "../math", package = "winter-math", default-features = false }
blake3 = { version = "1.0", default-features = false }
sha3 = { version = "0.9", default-features = false }
hashbrown = { version = "0.9.1", optional = true, default-features = false, features = ["ahash", "inline-more"] }
rayon = { version = "1.5", optional = true }

[dev-dependencies]
criterion = "0.3"
proptest = "1.0"
sha2 = "0.9"
rand = "0.8"
